### ISSUE TITLE
Update to Gradle 7

### ISSUE THREAD

**Issue by dblock** [opensearch-project/common-utils#101]
**Is your feature request related to a problem? Please describe.**
The OpenSearch Plugins are still built using Gradle 6.6.x whereas the Gradle release train has moved to 7.x already. The OpenSearch core is about to be switched to Gradle 7.3 (see please opensearch-project/OpenSearch#1609), it would make sense to switch all plugins to Gradle 7.3 as well.

**Describe the solution you'd like**
 Update Gradle to 7.3

**Describe alternatives you've considered (Optional)**
N/A

**Additional context**
See please opensearch-project/OpenSearch#1246 and opensearch-project/opensearch-plugins#107

**Comment by ohltyler** [comment]
Because of [this PR](https://github.com/opensearch-project/OpenSearch/pull/2033) merged, all 1.3.0 builds are broken. This should be done for this minor release instead of waiting for 2.0.0 major release now.

Tracking ticket in opensearch-build: https://github.com/opensearch-project/opensearch-build/issues/1587

**Comment by ohltyler** [comment]
@opensearch-project/common-utils can we get someone to help take care of this ASAP? Thank you

**Comment by ohltyler** [comment]
Change has now been reverted for 1.x and will re-tag as 2.0.0 issue: https://github.com/opensearch-project/OpenSearch/pull/2047
